name: image_overlay_editor
description: A super simple Flutter package for editing images with overlays. Perfect for apps that need to upload edited images to cloud storage or databases.
version: 1.0.0
homepage: https://github.com/yourusername/image_overlay_editor

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed for this package